apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
    version: blue
spec:
  containers:
    - name: front-end
      image: louisvernon/kubernetes-101-hello:blue
      ports:
        - containerPort: 9000
